group: less-iterations

graph_class:
  WS:
    n: [40]
    p: [0.9]
    k: [8]
    two_cells: [50]
    flows: [16]
    flow_mult: [1]
    flow_add: [0]
    noise_mult: [0.3]
    independent_flows: [True]
    remove_unused_edges: [False]

inference:
  mat_fact:
    n_best: [5]
    n_candidates: [-1]
    harmonic_method_and_params:
      2: {}
    candidate_selection_and_params:
      # 1: {}
      5: { w_approx_F: [1], w_boundary_one: [0], w_close_discrete: [0] } # Weighted
    discretizing_method_and_params:
      1: {}
    lr_method_and_params:
      1:
        r: [10]
