group: less-iterations

graph_class:
  ER:
    n: [40]
    p: [0.9]
    two_cells: [50]
    flows: [64]
    flow_mult: [1]
    flow_add: [0]
    noise_mult: [0.3]
    independent_flows: [True]
    remove_unused_edges: [False]
  BA:
    n: [40]
    m: [6]
    two_cells: [50]
    flows: [64]
    flow_mult: [1]
    flow_add: [0]
    noise_mult: [0.3]
    independent_flows: [True]
    remove_unused_edges: [False]
  WS:
    n: [40]
    p: [0.9]
    k: [8]
    two_cells: [50]
    flows: [64]
    flow_mult: [1]
    flow_add: [0]
    noise_mult: [0.3]
    independent_flows: [True]
    remove_unused_edges: [False]

inference:
  mat_fact:
    n_best: [1, 8]
    n_candidates: [8, -1]
    harmonic_method_and_params:
      2: {}
    candidate_selection_and_params:
      1: {}
    discretizing_method_and_params:
      1: {}
    lr_method_and_params:
      1:
        r: [8]
      2:
        r: [8]
      3:
        r: [8]
        w_boundary_one: [1]
        w_approx_F: [1]
        w_close_discrete: [1]
        iterations: [40, 200]
      4:
        r: [8]
      5:
        r: [8]
        alpha: [5]
        # alpha: [1, 2, 5]
